### ISSUE TITLE
Failed to validate the SSL certificate for packages.cloud.google.com:443.

### ISSUE THREAD

**Issue by kamal2222ahmed** [nextbreakpoint/kubernetes-playground#9] opened 2019-05-10 11:39 UTC
k8s1: TASK [k8s-base : Ensure Google Cloud Apt Key] **********************************
    k8s1: fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for packages.cloud.google.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)."}

**Comment by nextbreakpoint** [comment] 2019-11-17 21:27
Sorry, I haven't been active on the project for a while. Recently I have updated my scripts and I didn't notice any issue.

**Comment by nextbreakpoint** [comment] 2019-12-22 18:55
closing because I can't reproduce it

**Closed by nextbreakpoint** 2019-12-22 18:55 UTC
