### ISSUE TITLE
The following packages have unmet dependencies:", " kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed"]}

### ISSUE THREAD

**Issue by kamal2222ahmed** [nextbreakpoint/kubernetes-playground#10] opened 2019-05-10 14:35 UTC
```
k8s1: TASK [k8s-base : Ensure kubelet] ***********************************************
    k8s1: fatal: [localhost]: FAILED! => {"cache_update_time": 1557498804, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'kubelet=1.13.4-00'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed"]}```

**Comment by nextbreakpoint** [comment] 2019-11-17 21:27
Sorry, I haven't been active on the project for a while. Recently I have updated my scripts and I didn't notice any issue.

**Comment by nextbreakpoint** [comment] 2019-12-22 18:55
closing because I can't reproduce it

**Closed** 2019-12-22 18:54 UTC
